In [1]:
# Install OpenCV
!pip install opencv-python

You are using pip version 9.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [3]:
import cv2

cv2.__version__

'3.4.4'

In [4]:
from IPython.display import Image
Image(url = 'foto.jpg')


In [5]:
Image(url = 'foto2.jpg')

In [8]:
# Using haarcascade method

params = 'haarcascade_frontalface_alt.xml'

classifier = cv2.CascadeClassifier(params)

image1 = cv2.imread('image1.jpg')
image2 = cv2.imread('image2.jpg')

In [33]:
# Converting to gray scale
grayImage1 = cv2.cvtColor(image1, cv2.COLOR_BGR2GRAY)
grayImage2 = cv2.cvtColor(image2, cv2.COLOR_BGR2GRAY)

cv2.imwrite('image1Gray.jpg', grayImage1)
Image(url = 'image1Gray.jpg')


cv2.imwrite('image2Gray.jpg', grayImage2)
Image(url = 'image2Gray.jpg')

In [21]:
facesOfImage1 = classifier.detectMultiScale(grayImage1, scaleFactor = 1.1, minNeighbors = 10, minSize = (30,30))
facesOfImage2 = classifier.detectMultiScale(grayImage1, scaleFactor = 1.1, minNeighbors = 10, minSize = (30,30))

print(type(facesOfImage1))
print(facesOfImage1)

<class 'numpy.ndarray'>
[[159  49  44  44]
 [226  50  48  48]
 [847  25  50  50]
 [848 136  47  47]
 [ 61  67  49  49]
 [680  79  48  48]
 [542  44  45  45]
 [617  47  41  41]
 [294 108  45  45]
 [801 110  47  47]
 [521 113  46  46]
 [594 115  49  49]
 [177 121  47  47]
 [ 89  23  43  43]
 [560 374  50  50]
 [639 380  46  46]
 [376  36  48  48]
 [409  99  48  48]
 [311  23  52  52]
 [759 358  51  51]
 [883 373  54  54]
 [ 98 339  54  54]
 [305 360  58  58]
 [388 380  52  52]]


In [22]:
for(x,y, width, height) in facesOfImage1:
    cv2.rectangle(image1, (x, y), (x+width, y+height), (0,0,255), 10)

In [24]:
cv2.imwrite('facesOfImage1Recognized.jpg', image1)
Image(url = 'facesOfImage1Recognized.jpg')

In [32]:
facesOfImage2 = classifier.detectMultiScale(grayImage2, scaleFactor = 1.3, minNeighbors = 100, minSize = (50,50))

for(x,y, width, height) in facesOfImage2:
    cv2.rectangle(image2, (x, y), (x+width, y+height), (0,0,255), 150)
    
cv2.imwrite('facesOfImage2Recognized.jpg', image2)
Image(url = 'facesOfImage2Recognized.jpg')